language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install: pip install .[dev]
script: py.test --cov scrapelib
after_success:
    - coveralls
notifications:
    email:
        - dev@jamesturk.net
