language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install: pip install mock pytest pytest-cov coveralls requests>=2.0 --upgrade
script: py.test --cov scrapelib
after_success:
    - coveralls
notifications:
    email:
        - james.p.turk@gmail.com
