dist: xenial
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
install: pip install .[dev]
script: 
    - py.test --cov scrapelib
    - flake8 scrapelib
after_success:
    - coveralls
notifications:
    email:
        - dev@jamesturk.net
